const String appName = "Twekl Test App";
const String noInternetError = "Please Check Your Internet Connection";
const String notFoundError = "Resource isn't Found";
const String notAuthorizedError = "not Authorized User";
const String badRequestError = "Bad Request Error";
const String serverError = "Server Error";
const String requestCancelledError = "request Cancelled Error";
const String otherError = "Other Error";
const String noResponseError = "There is No Response Error";
